### ISSUE TITLE
Typo in main in autoXRD/spectrum_generation/impurity_peaks.py

### ISSUE THREAD

**Issue by Pepe-Marquez** [njszym/XRD-AutoAnalyzer#10]
In `autoXRD/spectrum_generation/impurity_peaks.py` line 177 reads `def main(struc, num_impure, imput_amt=70.0, min_angle=10.0, max_angle=80.0, ref_dir='References')`. `imput_amt` should be replcaed by `impur_amt`.

**Comment by njszym** [comment]
Fixed, thanks Pepe!
