### ISSUE TITLE
Inference takes hours+

### ISSUE THREAD

**Issue by AndySAnker** [njszym/XRD-AutoAnalyzer#3]
Thanks for making this interesting work open source! 

I am interested to trying the ML models on my own data. Therefore, I followed the steps in the Readme file.
1. git clone https://github.com/njszym/XRD-AutoAnalyzer.git
2. pip install . --user
3. python run_CNN.py (in the Example folder)

However, when doing so, the predictions takes hours in line 68 of the run_CNN.py script. I have attached a screenshot of the loading bar that does not proceed. I do not know the exact time that it takes as I terminated the script after 3 hours of not processing a single XRD pattern. Have you seen this issue before?

![Skærmbillede 2023-12-01 kl  14 43 44](https://github.com/njszym/XRD-AutoAnalyzer/assets/41198747/6c031767-5050-428d-b7e5-9094a2920860)

**Comment by njszym** [comment]
Hi Andy, thanks for bringing this issue up! To help diagnose it, can you try turning parallelization off?

To do this, you can edit line 21 of run_CNN.py to: parallel = False

And then try running the script again. Let me know if this helps or if the issue persists.

**Comment by AndySAnker** [comment]
Hi Nathan
Thanks for the rapid response.

When I turn off parallelization, I instead get an memory error after a few seconds:
zsh: segmentation fault  python run_CNN.py

My guess is that this is a good sign, and the model takes some memory to run? 
I will try to run it on a computer with more memory and return with a status.
