### ISSUE TITLE
Customdropout issue

### ISSUE THREAD

**Issue by mayisme** [njszym/XRD-AutoAnalyzer#4]
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoyf/Documents/Jupyterlab/XRD-AutoAnalyzer/autoXRD/spectrum_analysis/__init__.py", line 733, in classify_mixture
    mixtures, confidences, backup_mixtures, scalings, spectra = spec_analysis.suspected_mixtures
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoyf/Documents/Jupyterlab/XRD-AutoAnalyzer/autoXRD/spectrum_analysis/__init__.py", line 91, in suspected_mixtures
    self.model = tf.keras.models.load_model(self.model_path, custom_objects={'CustomDropout': CustomDropout}, compile=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/saving/saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 133, in load_model_from_hdf5
    model = saving_utils.model_from_config(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/legacy/saving/saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/legacy/saving/serialization.py", line 495, in deserialize_keras_object
    deserialized_obj = cls.from_config(
                       ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/models/sequential.py", line 327, in from_config
    layer = saving_utils.model_from_config(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/legacy/saving/saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/legacy/saving/serialization.py", line 473, in deserialize_keras_object
    (cls, cls_config) = class_and_config_for_serialized_keras_object(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/legacy/saving/serialization.py", line 354, in class_and_config_for_serialized_keras_object
    raise ValueError(
ValueError: Unknown layer: 'CustomDropout'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[4], line 73
     69     model_path = 'Model.h5'
     71 # Get predictions from XRD analysis
     72 results['XRD']['filenames'], results['XRD']['phases'], results['XRD']['confs'], results['XRD']['backup_phases'], \
---> 73     results['XRD']['scale_factors'], results['XRD']['reduced_spectra'] = spectrum_analysis.main('Spectra', 'References',
     74     max_phases, cutoff_intensity, min_conf, wavelength, min_angle, max_angle, parallel, model_path, is_pdf=False)
     76 if inc_pdf:
     77     # If specified, get predictions from PDF analysis
     78     model_path = 'Models/PDF_Model.h5'

File ~/Documents/Jupyterlab/XRD-AutoAnalyzer/autoXRD/spectrum_analysis/__init__.py:878, in main(spectra_directory, reference_directory, max_phases, cutoff_intensity, min_conf, wavelength, min_angle, max_angle, parallel, model_path, is_pdf)
    872 def main(spectra_directory, reference_directory, max_phases=3, cutoff_intensity=10, min_conf=10.0,wavelength='CuKa',
    873     min_angle=10.0, max_angle=80.0, parallel=True, model_path='Model.h5', is_pdf=False):
    875     phase_id = PhaseIdentifier(spectra_directory, reference_directory, max_phases,
    876         cutoff_intensity, min_conf, wavelength, min_angle, max_angle, parallel, model_path, is_pdf)
--> 878     spectrum_names, predicted_phases, confidences, backup_phases, scale_factors, reduced_spectra = phase_id.all_predictions
    880     return spectrum_names, predicted_phases, confidences, backup_phases, scale_factors, reduced_spectra

File ~/Documents/Jupyterlab/XRD-AutoAnalyzer/autoXRD/spectrum_analysis/__init__.py:699, in PhaseIdentifier.all_predictions(self)
    697         else:
    698             print('Running XRD analysis')
--> 699         all_info = list(tqdm(pool.imap(self.classify_mixture, spectrum_filenames),
    700             total=len(spectrum_filenames)))
    702 else:
    703     all_info = []

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tqdm/std.py:1181, in tqdm.__iter__(self)
   1178 time = self._time
   1180 try:
-> 1181     for obj in iterable:
   1182         yield obj
   1183         # Update and possibly print the progressbar.
   1184         # Note: does not call self.update(1) for speed optimisation.

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

ValueError: Unknown layer: 'CustomDropout'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

**Comment by njszym** [comment]
Thanks for brining this issue up. Can you let me know:
1) What steps/commands you took to train the model?
2) What command preceded this error? I assume it was during the execution of run_CNN.py?

Typically, this error arises when the model (Model.h5) was trained without custom dropout. But that should be included by default when you run construct_model.py.

**Comment by mayisme** [comment]
Hi, when I try to execute "!Python run_CNN.py" in the example folder with jupyterlab, the dropout issue came up.

**Comment by njszym** [comment]
Got it, thanks. Can you let me know what version of Python you are running? As well as what versions of tensorflow and keras you have installed?

**Comment by mayisme** [comment]
Hi，thanks for replying, I am using mac m1pro, the python version is 3.1.1, tensorflow and keras is the default version as i run python setup.py

**Comment by mayisme** [comment]
Sorry, my python version is  3.1.2, and the tensorflow version is '2.16.0rc0', the keras version is 3.0.5

**Comment by njszym** [comment]
Thanks. Can you try updating your python installation? XRD-AutoAnalyzer requires 3.6 or later. After updating, please try running the code again and let me know if the issue persists.

**Comment by mayisme** [comment]
sorry, the python version is 3.12.2, should I downgrade Python to 3.11?

**Comment by njszym** [comment]
Got it, that version of python should work fine. Can you try updating your tensorflow package to the latest version?

Also, to help isolate the issue, would you mind running this code (below) in the same folder as the Model.h5 file? And letting me know if this produces the same error?

```
import tensorflow as tf

# Used to apply dropout during training *and* inference
class CustomDropout(tf.keras.layers.Layer):

    def __init__(self, rate, **kwargs):
        super(CustomDropout, self).__init__(**kwargs)
        self.rate = rate

    def get_config(self):
        config = super().get_config()
        config.update({
            "rate": self.rate
        })
        return config

    # Always apply dropout
    def call(self, inputs, training=None):
        return tf.nn.dropout(inputs, rate=self.rate)



model = tf.keras.models.load_model('Model.h5', custom_objects={'CustomDropout': CustomDropout}, compile=False)

```

**Comment by mayisme** [comment]
Thanks a lot, the issue is solved!
